// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cats.sql

package db

import (
	"context"
)

const createCat = `-- name: CreateCat :one
INSERT INTO	cats (name, age) VALUES (?, ?) RETURNING id, name, age
`

type CreateCatParams struct {
	Name string `json:"name"`
	Age  int64  `json:"age"`
}

func (q *Queries) CreateCat(ctx context.Context, arg CreateCatParams) (Cat, error) {
	row := q.db.QueryRowContext(ctx, createCat, arg.Name, arg.Age)
	var i Cat
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}

const deleteCat = `-- name: DeleteCat :exec
DELETE FROM cats WHERE id = ?
`

func (q *Queries) DeleteCat(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCat, id)
	return err
}

const getCat = `-- name: GetCat :one
SELECT id, name, age FROM cats WHERE id = ? LIMIT 1
`

func (q *Queries) GetCat(ctx context.Context, id int64) (Cat, error) {
	row := q.db.QueryRowContext(ctx, getCat, id)
	var i Cat
	err := row.Scan(&i.ID, &i.Name, &i.Age)
	return i, err
}

const getCats = `-- name: GetCats :many
SELECT id, name, age FROM cats
`

func (q *Queries) GetCats(ctx context.Context) ([]Cat, error) {
	rows, err := q.db.QueryContext(ctx, getCats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cat
	for rows.Next() {
		var i Cat
		if err := rows.Scan(&i.ID, &i.Name, &i.Age); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCat = `-- name: UpdateCat :exec
UPDATE cats SET name = ?, age= ? 	WHERE id = ?
`

type UpdateCatParams struct {
	Name string `json:"name"`
	Age  int64  `json:"age"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateCat(ctx context.Context, arg UpdateCatParams) error {
	_, err := q.db.ExecContext(ctx, updateCat, arg.Name, arg.Age, arg.ID)
	return err
}
